### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by ghost** [davidmezzetti/webelapse#2]
Hi, how to fix this error? best regards
```
┌──(root㉿user)-[~/webelapse]
└─# webelapse
internal/modules/cjs/loader.js:1015
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/local/lib/node_modules/webelapse/node_modules/leven/index.js
require() of ES modules is not supported.
require() of /usr/local/lib/node_modules/webelapse/node_modules/leven/index.js from /usr/local/lib/node_modules/webelapse/record.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/local/lib/node_modules/webelapse/node_modules/leven/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/webelapse/record.js:16:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by davidmezzetti** [comment]
This error appears to come with Node.js 12.x. Are you using that version? I will keep this open and look at it further but in the meantime perhaps an older version of Node.js works?

**Comment by ghost** [comment]
```
Hi, which version i need to have?
current version:
node -v
v12.22.9
```

**Comment by davidmezzetti** [comment]
Looks like it is an issue with a dependent package.

After you install webelapse, can you run the following?

```
npm install leven@3.1.0
```

**Comment by davidmezzetti** [comment]
Also run this:

```
npm install commander@6.2.1
```

Those should get it working. I'll keep this issue open to either update package.json to use only those versions or figure out what changed so webelapse is compatible with the latest versions of commander and leven.

**Comment by davidmezzetti** [comment]
A new release of webelapse was pushed to npm to fix these broken dependencies.
